[telegram]
token = "123456:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"
admins = [1234567]
workers = 1 # number of python-telegram-bot workers. One worker is more than enough
timeout = 120 # requests timeout in seconds
completed_torrents_notification = 0 # id of a chat to notify when a torrent is completed. 0 to disable
new_torrents_notification = 0 # id of a chat to notify when a new torrent is added. 0 to disable

[qbittorrent]
url = "http://127.0.0.1:8080/"
login = "admin"
secret = "adminadmin"
toggle_torrents_queueing_every_night = false # if enabled, torrents queueing will be disabled and re-enabled every night
added_torrents_tag = "telegram bot" # a tag to add to the torrents added through the bot. "false", 0, or empty to disable
